default:
  image: "python:3.7"

include:
  - project: dke/apps/templates/job-templates
    #ref: develop
    file: job-templates.yml
  - project: nse/ci
    file:
      - /ci/lib/common.yml
      - /ci/jobs/build-package.yml
      - /ci/jobs/build-wheels.yml
      - /ci/jobs/publish-package.yml
      #- /ci/jobs/tag.yml

stages:
  - unit-test
  - lint-check
  - build
  - publish

build-package:
  rules:
    - when: on_success
publish-package:
  rules:
    - if: $CI_COMMIT_TAG
.tag:
  rules:
    - if: $CI_COMMIT_TAG

.add_staging_SSL:
  script:
    - CA_BUNDLE=$(python3 -c "import certifi; print(certifi.where())")
    - cat $BBP_CA_CERT >> $CA_BUNDLE
    - export SSL_CERT_FILE=$CA_BUNDLE

unit_test:
  stage: unit-test
  extends: .unit-tests
  before_script:
    - pip install -r requirements.txt
    - pip install .[dev]
  script:
    #- !reference [.add_staging_SSL, script]
    - CA_BUNDLE=$(python3 -c "import certifi; print(certifi.where())")
    - cat $BBP_CA_CERT >> $CA_BUNDLE
    - export SSL_CERT_FILE=$CA_BUNDLE
    #- !reference [.unit-tests, script]
    - echo 'The job variables to be used for pytest --cov are SRC_PROJECT (value is $SRC_PROJECT) and TEST_FOLDER (value is $TEST_FOLDER)'
    - pytest --cov $SRC_PROJECT $TEST_FOLDER --color yes --junitxml report.xml
  variables:
    SRC_PROJECT: '$CI_PROJECT_PATH'
    TEST_FOLDER: 'tests'
    NEXUS_STAGING_TOKEN: '$NEXUS_STAGING_TOKEN'

lint_check:
  stage: lint-check
  extends: .flake8
  allow_failure: true
