default:
  image: "python:3.7"

include:
  - project: dke/apps/templates/job-templates
    #ref: develop
    file: job-templates.yml
  - project: nse/ci
    file:
      - /ci/lib/common.yml
      - /ci/jobs/build-package.yml
      - /ci/jobs/build-wheels.yml
      - /ci/jobs/publish-package.yml
      #- /ci/jobs/tag.yml

stages:
  - unit-test
  - lint-check
  - build
  - publish

build-package:
  rules:
    - when: on_success
publish-package:
  rules:
    - if: $CI_COMMIT_TAG
.tag:
  rules:
    - if: $CI_COMMIT_TAG

unit_test:
  stage: unit-test
  extends: .unit-tests
  before_script:
    - pip install -r requirements.txt
    - pip install .[dev]
    - CA_BUNDLE=$(python3 -c "import certifi; print(certifi.where())")
    - cat $BBP_CA_CERT >> $CA_BUNDLE
  variables:
   SRC_PROJECT: '$CI_PROJECT_PATH'
   TEST_FOLDER: 'tests'
   NEXUS_STAGING_TOKEN: '$NEXUS_STAGING_TOKEN'

lint_check:
  stage: lint-check
  extends: .flake8
  allow_failure: true
