#!/usr/bin/env python

import imp

from setuptools import setup, find_packages

VERSION = imp.load_source("", "src/bba_dataset_push/__init__.py").__version__

setup(
    name="bba_data_push",
    author="BlueBrain DKE",
    author_email="nabil.alibou@epfl.ch",
    version= VERSION,
    description="Package to perform verification on the integrity of the data generated by the Blue Brain Atlas Pipeline. The dataset formats supported are : volumetric .nrrd, .OBJ meshes and .hdf5 containing cell positions",
    download_url="ssh://bbpcode.epfl.ch/code/a/dke/bba_data_integrity_check",
    license="BBP-internal-confidential",
    python_requires='>=3.6.0',
    install_requires=[
        'nexusforge>=0.5.0',
        'click>=7.0',
        'numpy>=1.19',
        'pynrrd>=0.4.0',
        'PyYAML>=5.3.1',
    ],
    packages=find_packages(),
    include_package_data=True,
    entry_points={
        'console_scripts': 
            ['bba-data-push=bba_dataset_push.bba_data_push:start']
    },
)
