import logging
from bba_data_push.bba_dataset_push import _initialize_pusher_cli, push_cellcomposition

logging.basicConfig(level=logging.INFO)
L = logging.getLogger(__name__)

forge_config_file = "https://raw.githubusercontent.com/BlueBrain/nexus-forge/master/examples/notebooks/use-cases/prod-forge-nexus.yml"

nexus_env = "https://staging.nise.bbp.epfl.ch/nexus/v1"
nexus_org = "bbp"
nexus_proj = "atlasdatasetrelease"
nexus_token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5T0R3Z1JSTFVsTTJHbFphVDZjVklnenJsb0lzUWJmbTBDck1icXNjNHQ4In0.eyJleHAiOjE2NzE3MzA2OTIsImlhdCI6MTY3MTcwMTkwMiwiYXV0aF90aW1lIjoxNjcxNzAxODkyLCJqdGkiOiIyZmI1NjkyZS0wYmE2LTQ5NzYtYjExMS1lZDEwMzJlZjJiMDciLCJpc3MiOiJodHRwczovL2JicGF1dGguZXBmbC5jaC9hdXRoL3JlYWxtcy9CQlAiLCJhdWQiOiJodHRwczovL3NsYWNrLmNvbSIsInN1YiI6ImY6MGZkYWRlZjctYjJiOS00OTJiLWFmNDYtYzY1NDkyZDQ1OWMyOmxjcmlzdGVsIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYmJwLW5pc2UtbmV4dXMtZnVzaW9uIiwibm9uY2UiOiIzZjA5NmQ3ZWU2Yzc0ZGY1YTlmODBlZWJiZGEyMDIyNiIsInNlc3Npb25fc3RhdGUiOiJmMTFjZjQ4MC1hYjEyLTRiMDAtODI0Ni1hYzBlMjlhYTJhNjUiLCJhY3IiOiIwIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImJicC1wYW0tYXV0aGVudGljYXRpb24iLCJvZmZsaW5lX2FjY2VzcyIsInVzZXIiLCJkZWZhdWx0LXJvbGVzLWJicCJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Imh0dHBzOi8vc2xhY2suY29tIjp7InJvbGVzIjpbInNsYWNrX3VzZXJfcm9sZSJdfX0sInNjb3BlIjoib3BlbmlkIG5leHVzIHByb2ZpbGUgbG9jYXRpb24gZW1haWwiLCJzaWQiOiJmMTFjZjQ4MC1hYjEyLTRiMDAtODI0Ni1hYzBlMjlhYTJhNjUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6Ikxlb25hcmRvIENyaXN0ZWxsYSIsImdyb3VwcyI6WyIvYmJwLWRldi1wcm9qMTA5IiwiL2JicC1ka2UtZGV2IiwiL2JicC1kZXYtcHJvajY0IiwiL2JicC1kZXYtcHJvajExNiIsIi9iYnAtb3UtZGtlIiwiL2JicC1kZXYtcHJvajg0IiwiL2JicC1ka2Utc3RhZ2luZyIsIi9iYnAtdXNlci1wcm9qMzkiLCIvYmJwLXVzZXItcHJvajY0IiwiL2JicC1vdS1uZXVyb2luZm9ybWF0aWNzIiwiL2JicC11c2VyLXJlbGVhc2UtbDIiLCIvYmJwLW91LW5leHVzIiwiL2JicC1kZXYtcHJvajE0MSIsIi9iYnAtZGV2LXByb2oxMTUiLCIvYmJwLW91LXNpbXVsYXRpb25uZXVyb3NjaWVuY2UiLCIvYmJwLWRzLWV4cGVyaW1lbnQiLCIvYmJwLXVzZXItcHJvajEwNiIsIi9iYnAtc3ZjLXZpeiIsIi9iYnAtZGV2LXByb2o1NSIsIi9iYnAtZGV2LXByb2o2MiIsIi9iYnAtZGV2LXByb2oxMzQiLCIvYmJwLWZ1bGwiLCIvYmJwLXN2Yy1naXRsYWIiLCIvYmJwLWNvbGxhYi1saW5rYWJsZS1hY2NvdW50cyIsIi9iYnAtZGV2LXByb2o4MyIsIi9iYnAtaXRjLWRhdGFpbnRlZ3JhdGlvbiIsIi9iYnAtZGV2LXByb2oxMDUiLCIvYmJwLWRldi1wcm9qODIiLCIvYmJwLXVzZXItcHJvajk0IiwiL2JicC1kZXYtcHJvajcyIiwiL2JicC11c2VyLXByb2oxMjMiLCIvYmJwLWRzLWhwYyIsIi9iYnAtZGtlLXByb2R1Y3Rpb24iLCIvYmJwLWRldi1wcm9qMTUyIiwiL2JicC1kZXYtcHJvajEzNiIsIi9iYnBfY29uZmx1ZW5jZSIsIi9iYnAtb3UtZXBmbCIsIi9iYnAtdXNlci1wcm9qMTE0IiwiL2JicC1zdmMtaHBjIiwiL2JicC11c2VyLXByb2o0MiIsIi9iYnAtZGV2LXByb2oxMzIiLCIvYmJwLWRldi1wcm9qMTQwIiwiL2JicC1zdmMtc2xhY2siLCIvYmJwLW5leHVzLWRldiIsIi9iYnAtc3RhZmYiLCIvYmJwLWRldi1oYnB2aXoiLCIvYmJwLXN2Yy1rdWJlcm5ldGVzIiwiL2JicC1zdmMtc3RhdHVzIiwiL2JicC1wdWJsaWNhdGlvbnMiLCIvYmJwLXVzZXItcHJvajMiXSwibG9jYXRpb24iOiJCMSAzIDI3OC4wNDUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJsY3Jpc3RlbCIsImdpdmVuX25hbWUiOiJMZW9uYXJkbyIsImZhbWlseV9uYW1lIjoiQ3Jpc3RlbGxhIiwiZW1haWwiOiJsZW9uYXJkby5jcmlzdGVsbGFAZXBmbC5jaCJ9.NlIehY9Nti51fBnHE04e5eWcxHAsv4wOTdfQYSf8YSD3bChWCAYz2kJKDtxSf5QA5Ofk-GrI1pXm75KpBQjdfGNIrHHPh8iPJrcNMHYW8xuhh-NukpQPrkqAutE75a7eqH1eRP9F17NsO6j3HXXX51RJ4MjK2aCDuODm8vdJ6zzLEYt13lFBkenjkBDjhSVyK_trh8FdpdOYar9xTTiRGq6-OCAmp2gUDkd6WEeVEQoFiMDz6EmQ03KZus7G_kzlXw7nqR-5fVORr_2bbDgjvzNB5sfcrcCk2B47SYmnSz01ruZUh3hmBB-LxzmqaBZFLHwkcOdYQMH6hYbUE7mD3g"

atlasrelease_id = "https://bbp.epfl.ch/neurosciencegraph/data/brainatlasrelease/c96c71a8-4c0d-4bc1-8a1a-141d9ed6693d"

folder = "/gpfs/bbp.cscs.ch/home/lcristel/BBP/atlas_pipelines/"
volume_path = folder+"cellCompVolume_small_path"
summary_path = folder+"cellCompSummary_density"

def test_push_cellcomposition():
    verbose = 2

    forge, verbose_L = _initialize_pusher_cli(verbose, forge_config_file, nexus_env, nexus_org, nexus_proj, nexus_token)
    cc_id = push_cellcomposition(forge, L, atlasrelease_id, volume_path, summary_path, "my_name", "my_description", "output_dir")
    L.info("The Nexus ID of the registered CellComposition is\n%s" % cc_id)
